application: gu-word-count
version: 15
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/.*
  script: tasks.app
  login: admin
- url: /static
  static_dir: static
- url: /api/.*
  script: api.app
- url: /admin
  script: admin.app
  login: admin
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on